# Generated by Django 5.0.1 on 2026-07-16 05:12

import catalog.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Muallif",
                "verbose_name_plural": "Mualliflar",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("uz", "O'zbekcha"),
                            ("ru", "Ruscha"),
                            ("en", "Inglizcha"),
                        ],
                        default="uz",
                        max_length=8,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=catalog.models.book_file_upload_path,
                    ),
                ),
                (
                    "epub_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=catalog.models.book_file_upload_path,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=catalog.models.book_file_upload_path,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=catalog.models.book_cover_upload_path,
                    ),
                ),
                (
                    "qr_token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "embedding_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("total_reads", models.PositiveIntegerField(default=0)),
                ("total_downloads", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="catalog.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kitob",
                "verbose_name_plural": "Kitoblar",
                "ordering": ["-created_at"],
            },
        ),
    ]
